Update microservice-main-build.yml

diff --git a/.github/workflows/microservice-main-build.yml b/.github/workflows/microservice-main-build.yml
--- a/.github/workflows/microservice-main-build.yml
+++ b/.github/workflows/microservice-main-build.yml
@@ -14,8 +14,8 @@ jobs:
         uses: actions/checkout@v2
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          repository: vcpsuthakar/microservice-app 
-          event-type: test_dispatch
+          repository: vcpsuthakar/common 
+          event-type: trigger-workflow-event
           client_payload: '{"github": ${{ toJson(github) }}}'
 
   #    - name: Wait for Repo B Workflow Completion
@@ -26,11 +26,11 @@ jobs:
   #        token: ${{ secrets.GITHUB_TOKEN }}
   #        event_type: trigger-workflow-event
 
-      - name: Check Workflow Status
-        run: |
-          if [[ "${{ steps.wait-for-workflow.outputs.status }}" == "completed" && "${{ steps.wait-for-workflow.outputs.conclusion }}" == "success" ]]; then
-            echo "Repo B workflow completed successfully."
-          else
-            echo "Repo B workflow failed or is still running."
-            exit 1
-          fi
+  #    - name: Check Workflow Status
+  #      run: |
+  #        if [[ "${{ steps.wait-for-workflow.outputs.status }}" == "completed" && "${{ steps.wait-for-workflow.outputs.conclusion }}" == "success" ]]; then
+  #          echo "Repo B workflow completed successfully."
+  #        else
+  #          echo "Repo B workflow failed or is still running."
+  #          exit 1
+  #        fi
